### ISSUE TITLE
Separation without training

### ISSUE THREAD

**Issue by kichel98** [kuielab/mdx-net#34]
Hello, is it possible to run separation using KUIELab-MDX-Net without training the model from scratch? Do you share some pretrained models? It would ease the evaluation of your solution and its usage in a real-case scenario.

**Comment by ws-choi** [comment]
Hi @kichel98 , I am sorry for the late reply.
I had been refactoring a document, which includes what you requested, but I could not finish it.
I will upload it as soon as possible but I am currently working on another project, unfortunately.

A good news is someone shared a detailed document.
[This guide](https://github.com/kuielab/mdx-net-submission/issues/10) was written by a third-party user, and it looks great and really helpful.
I hope it works for you.

**Comment by kichel98** [comment]
Thank you! I tested it - it is exactly what I needed.
