### ISSUE TITLE
Please can you explain me the meaning of these model settings

### ISSUE THREAD

**Issue by lyndonlauder** [kuielab/mdx-net#36]
l: 3
g: 32
k: 3
bn: 8

Please can you explain me what l,g,k and bn mean and the uses. Thank you.

**Comment by Zokhoi** [comment]
[k is kernel size](https://github.com/kuielab/mdx-net-submission/blob/master/models.py#L23)

From [paper on MDX-Net](https://arxiv.org/pdf/2111.12203.pdf#subsection*.4):
> Some source separation methods (Choi, 2021; Choi et al., 2020; Yin et al., 2020) have adopted
Frequency Transformation (FT) to capture frequency-to-frequency dependencies of the target
source. Both designed their FT blocks with fully connected layers, also known as linear layers.
For example, (Choi et al., 2020) proposed Time-Distributed Fully connected layers (TDF) to
capture frequency patterns observed in spectrograms of a singing voice. A TDF block is a
sequence of two linear layers. It is applied to a given input in the frequency domain. The first
layer downsamples the features to RdF/bne, where we denote the number of frequency bins
in a given spectrogram feature by F and the bottleneck factor that controls the degree of
downsampling by bn

bn is bottleneck factor.

In [another section](https://arxiv.org/pdf/2111.12203.pdf#subsection*.13) of the paper:
<blockquote>
We present a comparison between configurations of TFC-TDF-U-Net v1 and v2 as follows. <br />
This applies to all models regardless of the target source (we did not explore different model <br />
configurations for each source). In short, v2 is a more shallow but wider model than v1.

<table>
<thead>
<tr>
<th></th>
<th># blocks</th>
<th># convs per block</th>
<th>bn</th>
<th># freq bins</th>
<th># STFT frames</th>
<th>hop size</th>
</tr>
</thead>
<tbody>
<tr>
<th>v1</th>
<td>9</td>
<td>5</td>
<td>16</td>
<td>2048</td>
<td>128</td>
<td>1024</td>
</tr>
<tr>
<th>v2</th>
<td>11</td>
<td>3</td>
<td>8</td>
<td>2048</td>
<td>256</td>
<td>1024</td>
</tr>
</tbody>
</table>

The number of intermediate channels is increased/decreased after down/upsampling layers with <br />a linear factor of 32. Also, as mentioned in Section “TFC-TDF-U-Net v2,” we used different <br />n_fft for each source: (6144, 4096, 16384, 8192) for (vocals, drums, bass, other).
</blockquote>

l is conv per block and g is the linear factor.

Also for reference, [paper on TFC-TDF-UNet](https://arxiv.org/pdf/1912.02591.pdf)
